server:
  port: 9002
spring:
  application:
    name: customer-ui
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
    fetch-registry: true

hystrix:
  command:
    default:
      execution:
        isolationn:
          thread:
            timeoutInMilliseconds:  1000


feign:
  circuitbreaker:
    enabled: true